language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
before_install:

install:
  - pip install unittest2
  - pip install flask
  - pip install flask_bootstrap
  - pip install flask_sqlalchemy
  - pip install flask_wtf
  - pip install pathlib
script: python tests/test_suite.py
